### ISSUE TITLE
Support anonymization profiles implemented in CTP

### ISSUE THREAD

**Issue by fedorov** [commontk/dcmjs.org#21]
CTP config files are in a well-structured format, and have been used by a large community of users. It would be very helpful if those could be reused in dcmjs.org

**Comment by pieper** [comment]
We looked at this - the CTP format seems a bit ad hoc at first glance.  Is it actually well-structured?  Is it in a standard parsable format?

**Comment by bebbi** [comment]
I'd add that the main need might be to consider importing CTP scripts.
With a web native tool, config export/import becomes much less needed than some way of associating configs with unique urls or users. The point is to keep everything machine independent.

**Comment by fedorov** [comment]
I do not know what is the definition of "well-structured" and "parsable" in this context ...

I do not use all of the capabilities, but commands like "keep", "remove", "lookup", "hashuid" seem quite simple and intuitive. Here's a sample of the commands I use. All I can say - looks well-structured and parsable to me!

```
 <e en="T" t="00181020" n="SoftwareVersion">@keep()</e>
...
 <e en="T" t="00181200" n="DateOfLastCalibration">@incrementdate(this,@DATEINC)</e>
 <e en="T" t="00181400" n="AcquisitionDeviceProcessingDescription">@remove()</e>
<e en="T" t="0020000e" n="SeriesInstanceUID">@hashuid(@UIDROOT,this)</e>
 <e en="T" t="00200010" n="StudyID">@empty()</e>
...
 <e en="T" t="00200052" n="FrameOfReferenceUID">@hashuid(@UIDROOT,this)</e>
...
 <e en="F" t="00280301" n="BurnedInAnnotation">@if(ImageType,contains,"YES"){@quarantine()}{@keep()}</e>
```

Documentation looks quite nice: http://mircwiki.rsna.org/index.php?title=The_CTP_DICOM_Anonymizer

What exactly is the cause of concern?

**Comment by bebbi** [comment]
See my previous comment - another aspect is that we can have more declarative definitions and/or GUI controlled operations, which certainly needs to be done to get to any level of user friendliness. But I don't think the overhead of xml format is needed when working _inside_ the tool

**Comment by pieper** [comment]
My concern is something like the line below.  What is that line?  It's
not xml is it?  It looks like a programming language of some sort, but
not one that I know.  What are the execution rules?  It looks Turning
complete, but odd syntax.  If we were to parse it, we'd need to
implement a little interpreter that converts that 'language' into
something we can execute.  That seems like a big burden and a very
difficult task to ever verify.

 <e en="F" t="00280301"
n="BurnedInAnnotation">@if(ImageType,contains,"YES"){@quarantine()}{@keep()}</e>

On the other hand, expressing what I think is the same concept in
javascript would be something like:

if (dataset.BurnedInAnnotation) {

  dataset.quarantine();

} else {

  dataset.keep();

}

Note that my example is not the exact syntax used currently in dcmjs,
but my argument is that if you needed to tell a average programmer to
write some rules they would be more likely to be able to find support
and documentation for writing standard javascript.

Perhaps this is just a matter of subjective preference, but I didn't
see enough special value in the CTP syntax to make it worth adopting
it.  Worst case I guess one could imagine making an auto-translator
for the simple declarative pieces and then make people translate the
procedural parts themselves.

**Comment by fedorov** [comment]
I agree it is not perfectly self-explanatory. But javascript isn't either. Not for me at least.

If I read documentation for if command here http://mircwiki.rsna.org/index.php?title=The_CTP_DICOM_Anonymizer#Conditional_Functions, it makes sense to me.

**Comment by fedorov** [comment]
Who is your target user?

Do you see dcmjs.org be a replacement to CTP, or a convenience tool for one-off projects?

**Comment by bebbi** [comment]
CTP for dummies :)

**Comment by pieper** [comment]
Like I said, to me it's a tradeoff between a non-standard syntax and a
standard syntax that any programmer can learn and has a million examples of.

I'll repeat my question @fedorov, is CTP the only project that uses this
particular conditional function syntax?  I argue that's something we'd want
to avoid even if it were more elegant than javascript.

**Comment by jcfr** [comment]
Would it make sense to talk with the creator of CTP ? I think we could learn from their experience ... and may be understand how they would solve the problem with more modern tools.

**Comment by fedorov** [comment]
@pieper I missed the question whether CTP is the only project using that particular conditional function syntax. It is the only project I know of.

**Comment by pieper** [comment]
@jcfr I spoke with Justin at RSNA, one of the people at least partially involved.  I don't think CTP syntax is considered anything more than a convenient and workable method.  I'm glad it works for CTP purposes, but the topic of this issue is Andrey's suggestion that we should try to support it in dcmjs, which I don't agree with.

**Comment by fedorov** [comment]
by the way, Justin is a user, not developer.

CTP has a google group that you can use to reach out to the CTP broader community if you want to get feedback https://groups.google.com/forum/?hl=en#!forum/rsnas-ctpmirc-user-group

**Comment by bebbi** [comment]
A great developer resource for CTP is John Perry (dls.net).

CTP project hasn’t invented the anonymization config format, this dates back to good old caBIG times, it was called MIRC Field Center (must have been 2005 or earlier).
CTP adopted Field Center as a module and replaced (or rebranded) it.

I don’t think the question is about script quality or CTP developer opinions.
I think our primary goal is to make anonymization easy, rather than supporting CTP super users with existing configurations.
Let me expand a bit. In the end, image mapping consists of 2 parts.
#1 Anonymization - there are really not that many options, HIPAA and EU Privacy law are the reference, and for each “data value", the rule is, accept it, clean it, or remove it. If you require an exception, it needs to be explained and documented in the Informed Consent - whether it’s in a profile definition or not.
#2 Identifier mapping - there are a lot of options here. Putting useful stuff into Patient ID tag for nice PACS listing, populating Clinical Trial Module for some reason, etc. etc. Every workflow might have its preferences.

To make it easy,  we should try to automate 1. as much as possible (adding exceptions under #2), and make #2 really friendly (including storing & annotating good configs and making them available to everybody). In this sense, I don’t think our target users are users wanting to migrating their configs from CTP to dcmjs.org. Instead, it’s users that want to have a simple way of ensuring identifier removal & mapping according to their workflow. Ideally, providing additional advantages such as sharing and federating configurations to lots of places.
Those who have detailed expectations on their configurations should be able to re-create them in dcmjs.org - we currently have big gaps there but they’re covered under the topic of adding declarative mapping directives, presenting them in a user friendly way, and keep oversight over the full current configuration.

**Comment by pieper** [comment]
I agree with Stefan's points.

Let me add one more case, which is conditional handling of things like private tags or non-conforming input data.  It is often the case, for example in DWI processing, that critical data is included in the private tags that is known not to be patient identifying and is also known to be critical if the data is to be useful later on.  Sometimes those determinations can only be made conditionally on a number of other fields in the file, such as vendor, model number, acquisition type, and often specific software versions.  I believe that a real language is helpful in those situations.

Although arguably this is 'expert' usage, as Stefan has pointed out we didn't even see a way to implement the pharma use case using existing CTP and couldn't reasonably see a way to extend it.

**Comment by fedorov** [comment]
> our primary goal is to make anonymization easy

CTP user group might be helpful in providing feedback on what is easy

**Comment by fedorov** [comment]
or maybe not, since they are CTP users, and you want a fresh look. Still unsure who is your target user or group to collect feedback ...

This was probably totally not helpful, so please feel free to close the issue.

**Comment by pieper** [comment]
Your thoughtful and informed contributions are always helpful and welcome!

dcmjs is just a technology with a few demos.  Specific applications, like uploading clinical trial data will define the exact contours of the constraint space.

**Comment by fedorov** [comment]
FYI

> The DICOM Anonymizer in this version has an internal index of safe private elements

https://groups.google.com/forum/?hl=en#!topic/rsnas-ctpmirc-user-group/OqItV-p12g8

https://github.com/johnperry/CTP/blob/master/source/resources/PrivateTagDictionary.xml

http://mircwiki.rsna.org/index.php?title=The_DICOM_Anonymizer_Keep_Safe_Private_Elements_Feature

**Comment by bebbi** [comment]
Nice!

**Comment by pieper** [comment]
Yes, very helpful!
